### ISSUE TITLE
Can't switch between primer sets

### ISSUE THREAD

**Issue by mattsoup** [bwlang/primer_monitor#34]
I'm not sure if it's temporary, but the last couple hours I keep getting the below error after waiting ~a minute or so when trying to switch between primer sets:

![Screen Shot 2021-08-20 at 12 00 18 PM](https://user-images.githubusercontent.com/28735187/130262013-1f73252e-5683-4824-92e5-e24e1803dd51.png)

**Comment by bwlang** [comment]
this is now resolved
