### ISSUE TITLE
Add a way to send a link to a specific set of presets to /organisms/SARS-CoV-2/lineage_variants

### ISSUE THREAD

**Issue by bwlang** [bwlang/primer_monitor#93]
I think we can do this simply by adding the parameters elected to the query string  (e.g append ?primer_set=ARTICv3,ARTICv4;lineage=BA.2.86

Having that feature can allow people to share a link to a specific visualization, e.g.:
<img width="1494" alt="image" src="https://github.com/bwlang/primer_monitor/assets/61636/a816e3f0-5a44-447c-9f1e-cf8bb27dfc9d">

**Comment by Valiec** [comment]
Agreed. Should I put this in a small update ahead of the multi-organism one, or bundle it into the multi-organism update?

**Comment by bwlang** [comment]
I think it's fine to bundle in .
